title: Hector Espert
email: hectorespertpardo@gmail.com
description: Linuxero, no limpio Windows.

remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Hector Espert
  tagline: Linuxero, no limpio Windows.
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/portfolio.png"
  dark_mode: true
  sitemap: true

  social_links:
    twitter: blackleg
    github: hectorespert
    linkedIn: in/hectorespert

  navigation:
    - title: Planted Pi
      url: "/planted-pi"
